import React,{Component} from 'react'
import './App.css';
//import RestaurantPhoto from './Components/Restaurant.photo';
import RestaurantStatus from './Components/Restaurant.Status';
import RestaurantDiscription from './Components/Restaurant.Discription';
import RestaurantStickyBillboard from './Components/Restaurant.StickyBillboard';
import RestaurantMenuBlock from './Components/Restaurant.MenuBlock';
export default class App extends Component{

  

  render(){
    
    return(
      <div id="App">
        <RestaurantStickyBillboard />
        <RestaurantStatus/>
        <RestaurantDiscription />
        <RestaurantMenuBlock />
        <div>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
          換行
          <br></br>
        </div>
      </div>
    )
  }
}



